---
name: Build centos6.10

on:
  pull_request:
  push:
    paths:
      - 'centos-6.10/**'
      - '.github/workflows/build-centos6.10.yml'
  schedule:
    - cron: '12 3,6 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd centos-6.10 && docker build -t docker-centos-6.10 .

      - name: Run the built image.
        run: docker run --name test-centos-6.10 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos-6.10

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-centos-6.10 env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: buluma/setup-buildx-action@0.1.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: centos-6.10/
          file: centos-6.10/Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/arm64/v8,linux/ppc64le,linux/386
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          tags: ${{ github.repository }}:centos6.10, ${{ github.repository }}:6.10
