---
name: Build centos7

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '40 *,* * * *'

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd centos7 && docker build -t docker-centos7 .

      - name: Run the built image.
        run: docker run --name test-centos7 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos7

      # - name: Verify Ansible is accessible in the built image.
        # run: docker exec --tty test-centos7 env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: centos7/
          file: centos7/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:centos7, ${{ github.repository }}:centos7.9.2009
