---
name: Build centos8

on:
  pull_request:
  push:
    paths:
      - 'centos8/**'
      - '.github/workflows/build-centos8.yml'
  schedule:
    - cron: '1 5,17 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test building image.
        run: cd centos8 && docker build -t docker-centos8 .

      - name: Run the built image.
        run: docker run --name test-centos8 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos8

      # - name: Verify Ansible is accessible in the built image.
        # run: docker exec --tty test-centos7 env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: buluma/setup-buildx-action@0.1.0

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: centos8/
          file: centos8/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:centos8, ${{ github.repository }}:centos8.4.2105
