---
name: Build systemd

on:
  pull_request:
  push:
    paths:
      - 'systemd/**'
      - '.github/workflows/build-systemd.yml'
  schedule:
    - cron: '28 8,19 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test building image.
        # run: cd systemd && docker build -t docker-systemd .
        run: cd systemd && docker build --rm --no-cache -t httpd .

      - name: Run the built image.
        run: docker run --privileged --name httpd -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 -d  httpd
        # run: docker run --name test-systemd -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-systemd

      # - name: Verify Ansible is accessible in the built image.
        # run: docker exec --tty test-centos7 env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: buluma/setup-buildx-action@0.1.4
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v4
        with:
          context: systemd/
          file: systemd/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          tags: ${{ github.repository }}:systemd
